### ISSUE TITLE
text replace matthew -> harvey

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-harvey#5]

**Comment by eread-usgs** [comment]
I believe this is taken care of in #7

**Comment by jordansread** [comment]
I wasn't sure (up to y'all) if you also wanted to do a complete `matthew` to `harvey` text replace in the whole repo, so it would also scrub the code to make the conversion. It doesn't matter, since they are variable names, but it would be less confusing to others. @wdwatkins could whip up something quick I bet.

**Comment by wdwatkins** [comment]
Yeah shouldn't be hard
